== The reactive thinking: from OOP to streams

Forget everything you know about code, and look around. Modeling this world with code is not easy. As developers, we tend to follow counter-intuitive approaches. Since the 80's, object-oriented programming has been seen as a _silver bullet_. Every entity from our world is represented by an object containing fields and exposing methods. Most of the time, interacting with these objects is done using a blocking and synchronous protocol. You invoke a method and wait for a response. 

But... the world in which we are living is asynchronous. The interactions are done using events, messages, and stimuli. To overcome the limitations of the object orientation, many patterns and paradigms emerged. But, more recently, functional programming is making a come-back, not to replace the object-orientation, but to complement it. _Reactive programming_ is a functional event-driven programming approach that is used in combination with the regular object-oriented paradigm.

A few years ago, Microsoft created a reactive programming framework for .NET called http://reactivex.io/[Reactive eXtensions] (also called ReactiveX or RX). RX is an API for asynchronous programming with **observable streams**. This API has been ported to several languages such as Swift, JavaScript, Python, C++, and Java. 

Let's observe our world for a moment. Observe entities in motion, traffic jams, weather, conversations, financial markets. Things are moving and evolving concurrently. Multiple _things_ happen at the same time, sometimes independently, sometimes in an orchestrated manner. Each object is creating a _stream_ of events. For instance, your mouse cursor position is moving. The sequence of position is a stream. The number of people in the room may be stable, but someone can come in or go out, generating a new value. So we have another stream of values. There is a fundamental mantra behind reactive programming: _events are data and data are events_.

But don't be mistaken, reactive programming is not a silver bullet. Reactive programming and RX let you express business logic in term of streams of events, helping you with concurrency and error recovery; but don't think it's magic... because it's not. RX gives you superpowers when dealing with asynchronous scenarios, but it does not come without costs.

=== "Enough philosophy, I wanna see code"

Alright! Let's see the code. Can we start with our beloved XML? In the `pom.xml` file located at the source of the code repository, you can see a few dependencies. One of them is:

[source,xml]
----
<dependency>
    <groupId>io.reactivex.rxjava2</groupId>
    <artifactId>rxjava</artifactId>
    <version>x.y.z</version>
</dependency>                      
----

That's the only dependency you need to start using RX Java. 

Now open the `src/main/java/me/escoffier/lab/chapter1/Code1.java`:

[source,java]
----
include::../../src/main/java/me/escoffier/lab/chapter1/Code1.java[]
----

This is your first RX Java application. A couple of points to understand:

* `import io.reactivex.*;` imports the classes form RX Java
* `Observable<String>`: represents a stream of data (here `String`). Notice the class name, it invites you to _observe_ it.
* `Observable.fromIterable`: creates a stream (`Observable`) from a collection
* `stream.subscribe`: declare an observer consuming the data passing in the streams. The passed lambda is called for each item.

Run this example and you should see:

[source, txt]
----
Superman
Batman
Aquaman
Asterix
Captain America
----

A gentle note about `subscribe`... If you don't subscribe to a stream, nothing happens. None of the processing stages will be executed until you subscribe to it. This is very important to remember to avoid thousands of hours of debugging!

=== That's all?

Ok, not really impressive... But the true power of RX Java comes from its set of operators to manipulate the streams. Jump to `src/main/java/me/escoffier/lab/chapter1/Code2.java`:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter1/Code2.java[]
----

This example uses two operators:

1. `map`: for each item of the observed stream, apply the function - here transform the name to uppercase
2. `filter`: for each item of the observed stream (the uppercase names), select only names starting with an `A`.

Run this example, you should see:

[source, txt]
----
AQUAMAN
ASTERIX
----

There is a very important point to make here: operators consume items from a stream and produce a stream. The first part is simple to understand. Typically, for `filter`, it received `SUPERMAN` then `BATMAN` and so on. The second part is a bit more tricky. Let's take `map` as an example:

[source]
----
Input: Superman    Batman     Aquaman ... <- input stream
            |           |        |
Result:  SUPERMAN    BATMAN   AQUAMAN ... <- this is also a stream
----

It produces one value per received value, in other words, a sequence of value: it's also a stream.

=== Ready to see more

In this chapter, you have seen some very basic RX Java 2, there is a lot more... 
