== Single, Completable, Maybe and Flowable

In the previous chapters, we have used streams containing several items. In this chapter, we are going to see some specialized streams:

* Single - A stream emitting 1 item
* Maybe - A stream emitting 0 or 1 item
* Completable - A stream containing no items
* Flowable - A multi-item stream supporting back-pressure

=== Single

A `Single` is a specialized stream that only emits one item. It works like the `Observable` streams we have seen previously but is limited to operators that make sense for a single emission. Typically, `doOnNext` and `doOnComplete` are replaced by `doOnSuccess` that accept the produced item.

In `me.escoffier.lab.chapter3.Code1`, you can see how this new method is used:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code1.java[]
----

This specialization also affects the `subscribe` method and provides a new form accepting the result and the error in a _biconsumer_. In  `me.escoffier.lab.chapter3.Code2`, complete the code to use this new variant.

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code2_Solution.java[]
----
****

Singles are often used for asynchronous operations returning a single result, such as an HTTP request. The following example uses the Vert.x Web Client to retrieve a list of superheroes:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code3.java[]
----

`client().get("/heroes").rxSend()` returns a `Single<HttpResponse>`. The rest of the processing is called when the response is received from the server. 

_Super Heroes & Villains service_: the previous example is the first use of this service. It runs locally on `http://localhost:8080`. Don't forget to stop the example/exercise once done or the next run won't work (because of the port already used). If you want to see what is provided by the service check:

* http://localhost:8080/heroes
* http://localhost:8080/villains
* http://localhost:8080/heroes/random
* http://localhost:8080/villains/random
* http://localhost:8080/heroes/:id - replace `:id` by the id
* http://localhost:8080/villains/:id - replace `:id` by the id

=== Maybe

`Maybe` is a stream that can emit 0 or 1 item. It is useful because `Single` can't emit `null` (`null` is an illegal value). `Maybe` observers are notified:

* when a value is emitted using the `onSuccess` method,
* when the stream complete, without a value using the `onComplete` method,
* when an error is thrown using the `onError` method

Notice the subtlety about `onSuccess` and `onComplete`. The first one is called when there is a value. The second one is called when there is not. This behavior is shown in the class `me.escoffier.lab.chapter3.Code4`:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code4.java[]
----

The output of this code is:

[source]
----
[A] Received Superman
[B] Completed
----

`Maybe` is often used for methods that may return `null`. For example, an asynchronous version of a `findById` method would return a `Maybe`. Let's use `Maybe` to check if there is a superhero named "Yoda" and another one named "Clement". Open the `me.escoffier.lab.chapter3.Code5` class and fill the code. The output should be something like:

[source]
----
Loaded 727 heroes and villains
Yes, Yoda is a superhero
No, clement is not a superhero
----

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code5_Solution.java[]
----
****

Don't forget to stop the process once done.

=== Completable

`Completable` represents a stream not emitting a value but simply concerned with an _action_ being executed. As a consequence, it does not provide a `doOnNext` method as there is no _next_. It indicates the successful completion of a (potentially asynchronous) process or its failure:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code6.java[]
----

In `me.escoffier.lab.chapter3.Code7`, fill the code to write a simple message into a file. For this, use the method named `rxWriteFile` that accepts the path (such as `hello.txt`) and a `Buffer` (such as `Buffer.buffer("hello")`). It returns a `Completable` indicating when the file has been written to (and it the write has been successful).

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code7_Solution.java[]
----
****

=== Flowable and back pressure

So far, we have seen examples of streams that were pushing items to subscribers. However, there is an issue with this model. If your consumer cannot keep up with the pace, something bad is going to happen. Putting a buffer in between will only handle small bumps. This is where back-pressure comes into the picture. But first, let's illustrate the example.

In `me.escoffier.lab.chapter3.Code8`, we create a stream of integers and display them in the `subscribe` method after a small nap:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code8.java[]
----

It gives the following output:

[source]
----
Constructing item using 1
Received: 1
Constructing item using 2
Received: 2
Constructing item using 3
Received : 3
Constructing item using 4
Received: 4
----

If you run this example, everything is fine. Each emission is processed one by one, and one at a time from the source all the way down to the subscriber. This is because a single thread is involved in the process, making everything synchronous. It creates a serialized processing, no problem so far.

Now let's introduce a change of thread (`Schedulers` will be covered later - just trust us for now). This code is in `me.escoffier.lab.chapter3.Code9`:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code9.java[]
----

Running this example produces an output similar to the following one:

[source, java]
----
...
Constructing item using 707290
Constructing item using 707291
Constructing item using 707292
Constructing item using 707293
Received: 95
Constructing item using 707294
Constructing item using 707295
Constructing item using 707296
Constructing item using 707297
Constructing item using 707298
Constructing item using 707299
...
----

We have constructed many items, while the subscriber is only processing the item 95! The emissions of the numbers are too fast for the consumer, and because the emissions are being pushed into an unbounded buffer by `observeOn`, this can be the source of many problems such as... running out of memory.

To mitigate this issue, RX Java 2 provides a stream named `Flowable`. `Flowable` is like `Observable` (it may contain multiple items) but implements a back-pressure protocol. This protocol tells the source stream to emit items at a pace specified by the consumer. `Flowable` uses a protocol named http://www.reactive-streams.org/[Reactive Streams]. This specification has been introduced in Java 9 under the name `java.util.concurrent.Flow` and is becoming widely popular.

Let's revisit the previous example, but instead of `Observable.range`, let's use `Flowable.range`. This code is in `me.escoffier.lab.chapter3.Code10`:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter3/Code10.java[]
----

Running this example produces something like:


[source]
----
....
Constructing item using 123
Constructing item using 124
Constructing item using 125
Constructing item using 126
Constructing item using 127
Constructing item using 128
Received: 1
Received: 2
Received : 3
Received: 4
Received: 5
....
Constructing item using 221
Constructing item using 222
Constructing item using 223
Constructing item using 224
Received: 97
Received: 98
Received: 99
Received: 100
Received: 101
Received: 102
Received: 103
....
----

What we can see here is that the source emits a set of items (128) and then, 96 items have been processed by the rest of the flow. During that time, no items have been emitted. So the consumer is telling to the source that it can't handle more at that time, and the source stops emitting. When the consumer can finally handle more items, it requests more to the source. No more risk of OOM!

Notice that RX Java 2 provides some other back pressure strategies such as using buffers, or dropping data. Check the https://github.com/ReactiveX/RxJava/wiki/Backpressure-(2.0)[documentation] for further details on these strategies.

=== Conclusion

In this chapter, we have seen a few different specialized streams to handle various situations. The following table summarizes when to use what:

|===
|Type |Use case

|Single | asynchronous operation returning 1 result
|Maybe | asynchronous operation returning either 0 or 1 result
|Completable | asynchronous operation not returning a result. Indicates the completion
|Observable | sequence of data, no back pressure
|Flowable| sequence of data, back-pressured
|===

It's great to have all these types, but the true power of RX Java comes from its set of operators.

