== Stream Operators

We have already seen a few operators, such as `map`, `filter`, and the different `doOnX` method. In this section, we will introduce some more. We can't cover all of them, so we will just explore the most common ones.

=== Filter, First, Skip, Take...

This first set of operators allows us to select the set of items to re-emit from a source.

==== Filter 

The `filter` operator accepts a predicate checking if the received item should be forwarded. In `me.escoffier.lab.chapter4.Code1#main`, fill in the code to generate a stream containing only villains with _Queen_ in their name.

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code1_Solution.java[]
----
****

_Note_: On a `Single`, the `filter` method allows you to transform it as a `Maybe`.

==== First & Last

On `Observable` and `Flowable`, there are a set of _first_ operators that select the first items from a stream:

* `first(T def)` takes the first item, or emits the given default if the source stream is empty. This method returns a `Single`.
* `firstElement()` forwards the first item from the observed stream. This method returns a `Maybe` as the observed stream can be empty.
* `firstOrError()` forwards the first item from the observed stream. If the observed stream is empty, it emits an error

The `last` / `lastElement` / `lastOrError` operators are the mirror operators forwarding only the last items of the stream. 

==== Skip and Take

The `skip` operator creates a stream that skips the first items emitted by the observed stream and emits the remainder. `skip` accepts a number of items, but also provides a time-based variant skipping all items emitted during a given time window. `skipLast` is the mirror operator trimming the end of the stream. 

The `take` operator creates a stream which emits only the first items emitted by the observed stream. As `skip`, `take` provides a time-based variant and a `takeLast` variant.

Open the `me.escoffier.lab.chapter4.Code2` and edit the code to create a stream containing 10 villains that are from the 21 positions to 31 positions.

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code2_Solution.java[]
----
****

The output should look like this:

[source]
----
Loaded 727 heroes and villains
Anti-Monitor
Red Skull
Anti-Spawn
Red Mist
Redeemer II
Apocalypse
Rhino
Redeemer III
Arclight
Rick Flag
----

=== Default and Switch

Sometimes, when you realize that your stream is empty, you want to inject some _sensible_ defaults. That's what the `defaultIfEmpty` and `switchIfEmpty` operators are doing.

`me.escoffier.lab.chapter4.Code3` shows an example of `switchIfEmpty`. `switchIfEmpty` returns a stream, so potentially several elements as in:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code3.java[]
----


`me.escoffier.lab.chapter4.Code4` gives an example of `defaultIfEmpty`. It basically injects a default value if the observed stream is empty.

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code4.java[]
----

=== Scan and Reduce

Scan and reduce are two very close operators. They both take a seed (there are variants without) and an accumulator function. This function is called with the previous result and the item coming from the observed stream.

The `me.escoffier.lab.chapter4.Code5` illustrates these two operators.

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code5.java[]
----

Run this example and check the difference. `reduce` is emitting a single value when the observed streams are completed. `scan` emits all computed values, including the seed (0 (seed), 0 + 0, 0 + 1, 1 + 2...).

[source]
----
[Scan] Got 0
[Scan] Got 0
[Scan] Got 1
[Scan] Got 3
[Scan] Got 6
[Scan] Got 10
[Scan] Got 15
[Scan] Got 21
[Scan] Got 28
[Scan] Got 36
[Scan] Got 45
[Reduce] Got 45
----

Open the `me.escoffier.lab.chapter4.Code6` and `me.escoffier.lab.chapter4.Code7` and fill the code to use the `scan` and `reduce` methods. You will finally know if superheroes have more superpowers than supervillains.

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code6_Solution.java[]
----

----
include::../../src/main/java/me/escoffier/lab/chapter4/Code7_Solution.java[]
----
****

=== Mapping a stream to a collection and vice-versa

It's often required to accumulate items from a stream into a collection (only for bounded streams of course) or transforming a collection into a stream.

RX Java provides a set of methods to transform a stream into a collection such as `toList` (creating a list of items), `toMap` building a map and to `toMultiMap` building a `Map<K, Collection<V>>`. In the class `me.escoffier.lab.chapter4.Code8` you can see an example of the `toList` operator:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code8.java[]
----

To transform a collection into a stream, use `Observable.fromIterable` or `Flowable.fromIterable`. `fromArray` is also quite convenient.

=== FlatMap

`FlatMap` is **the** operator to understand. `FlatMap` is very powerful but requires a bit more explanation. `FlatMap` takes each item emitted by the observable stream and _maps_ it to another stream (this is the _map_ part). Then, it merges the emissions from the returned streams into a single stream (it's the _flat_ part).

The simplest usage of `flatMap` is to produce a stream of items out of a single item. For example, in `me.escoffier.lab.chapter4.Code9` you can see how the `flatMap` operator is used to produce a stream of words:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code9.java[]
----

You may wonder why the method is named `flatMapPublisher`, it's because by default `flatMap` returns a stream of the same type. So `Single.flatMap` returns a `Single`. Fortunately, the method `flatMapCompletable`, `flatMapMaybe` and `flatMapPublisher` (for `Flowable`) let us transform the type of streams.

`FlatMap` is also used as a composing operator to express a sequential composition. For example, chaining two HTTP requests as illustrated in `me.escoffier.lab.chapter4.Code10`:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code10.java[]
----

You can also use `flatMap` on a `Single` to execute a second request once the `Single` has completed as illustrated in `me
.escoffier.lab.chapter4.Code11`:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code11.java[]
----

=== Merge and Zip

RX Java also provides operators to merge streams or to associate items from different streams. 

The `mergeWith` operator merges the current stream with other ones. The produced stream contains all the items from the merged streams in the order of their emissions. If you prefer not mixing the items use `concatWith` but be aware it does not work for unbounded streams.

Open the class `me.escoffier.lab.chapter4.Code12` and fill the code to count the number of superpowers.

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code12_Solution.java[]
----
****

The `zipWith` operator associates items from different streams. It takes the _next_ items emitted by each stream and calls a function with all of them. For example, we can use this to generate superheroes vs. supervillains battles. Open the `me.escoffier.lab.chapter4.Code13` class and fill the code to generate fights between heroes and villains.

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code13_Solution.java[]
----
****

=== Error recovery

Even when using RX, errors and failures happen. I told you it's not a silver bullet. But, I've got a good news for you: there are operators to handle error recovery. 

Let's start with some _simple_ case. Imagine you want to emit a request to our Super Heroes and Villains service, but the service is not started. Something like the `me.escoffier.lab.chapter4.Code14` class:

[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code14.java[]
----

When you run this program, you get:

[source]
----
Oh no... something bad happened: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
----

Let's now use the `onErrorReturnItem` operator that let you recover from an error by injecting a default result. There is also a variant named `onErrorReturn` that let you decide of the value to return based on the error (`Throwable`). Edit the class to use the `onErrorReturnItem` or `onErrorReturn` to avoid recover from the error.

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code14_Solution.java[]
----
****

The `onErrorResumeNext` operator is similar to `onErrorReturnItem` but returns a stream. Basically, if an error happens, it replaces the stream with the given one. Open the `me.escoffier.lab.chapter4.Code15` class and use the `onErrorResumeNext` to inject another `Single`. You can use `Single.just` to create a stream with an already known value.

[.assignment]
****
[source, java]
----
include::../../src/main/java/me/escoffier/lab/chapter4/Code15_Solution.java[]
----
****

The `onErrorResumeNext` is quite useful when you want to execute another async operation when an initial one failed. It also can substitute a stream in error with a default stream similar to a _switchOnError_ operator (that does not exist).

The last error recovery mechanism we are going to see is very powerful but can be dangerous too. The `retry` operator re-subscribes to a stream that emitted an error. Its behavior depends on the cold/hot nature of the observed stream. On a cold stream, the resubscription restarts the stream from the beginning. It's very useful to retry a failed operation such as an HTTP call. The retry operator has several variants letting you decide whether or not you want to retry based on the error and the number of attempts.

=== Conclusion

This chapter introduced a few operators. RX Java 2 is proposing a lot more operators. Check the https://github.com/ReactiveX/RxJava/wiki/Alphabetical-List-of-Observable-Operators[operator list] to see the full list.

Now you have enough knowledge to start building an RX Java API.
